### ISSUE TITLE
Unable to find plugin "gatsby-source-confluence".

### ISSUE THREAD

**Issue by bradwoods** [daniel-simpson/gatsby-source-confluence#1]
When attempting to run Gatsby in dev mode I'm getting the following error message: `Unable to find plugin "gatsby-source-confluence"`.

Using Gatsby **v2.0.19**.

**Comment by daniel-simpson** [comment]
Hi @bradwoods, thanks for trying out gatsby-source-confluence :)

Before I dive any deeper, just confirming that you've manually installed this plugin inside of your gatsby project directory with the following command? 

`npm i --save gatsby-source-confluence`

**Comment by bradwoods** [comment]
hey mate, yep installed it manually

**Comment by daniel-simpson** [comment]
Any chance you're able to update gatsby from 2.0.19? That build is about 7 months old, and when debugging I've found that it seems to be looking for the plugin in the wrong directory:
```
Resolves correctly: => <projectDir>/node_modules/gatsby/dist/internal-plugins/query-runner
...
Failing: => <projectDir>/node_modules/gatsby/dist/internal-plugins/gatsby-source-confluence
```

**Comment by bradwoods** [comment]
Upgraded to 2.3.32 but still getting the same error.

**Comment by daniel-simpson** [comment]
For now can you please try cloning this repo into `plugins/gatsby-source-confluence`, I'll take a look at this shortly, sorry!

**Comment by daniel-simpson** [comment]
@bradwoods this should now be working in version [v1.0.3](https://github.com/daniel-simpson/gatsby-source-confluence/releases/tag/v1.0.3)

Thank you for pointing this out, it looks like you're the first person using my first plugin!

**Comment by bradwoods** [comment]
That's commit has fixed the issue, thanks mate. Do you have any examples of how to query the data?

**Comment by daniel-simpson** [comment]
This plugin uses CQL (Confluence Query Language) to select a list of confluence pages to be added to your Gatsby graphql schema. For more info on CQL you can use the following reference :)

https://confluence.atlassian.com/confcloud/confluence-search-syntax-724765423.html

Feel free to open up another issue or feature request (or even better, PR), if you have a use case other than what is catered for. It s a pretty simple plugin at the moment. 

Thanks!

**Comment by daniel-simpson** [comment]
FYI @bradwoods  I've also spun up a very basic example site that pulls data from a public confluence space, and points to where in the repo you can see the changes you'll need to add to create confluence pages as content in your site:

https://gatsby-source-confluence.netlify.com/

Thanks!
